language: go

sudo: false
services: 
  - redis
  - mysql
  - postgres

go:
  - 1.5
  - 1.6
  
before_script:
  - mysql -h localhost -u root --password='' < ./build/schema_create.sql
  - psql -c "create database testdb;" -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'postgres';" -U postgres
    psql -U postgres < build/postgres_create.sql
  - go get ./...
  - go get gopkg.in/redis.v3
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  
script:
  - go test ./... -cover -timeout 10s
