MySQLHost: localhost
MySQLPort: "3306"
MySQLUser: testuser
MySQLPass: testuser 
MySQLDB: testdb
RedisServer: localhost
RedisPort: 6379
# Whitelist indicates that torrent whitelisting is activated. When torrent
# whitelisting is activated, only pre-approved torrents can be served by
# Notorious
Whitelist: false
# UseEnvVariables allows environmental variables to be used instead of
# expliclitly defined config variables.
UseEnvVariables: true
