# MySQL Options. Set `UseMySQL` to `true` if mysql is desired for
# production/testing/anything.
# PostGres Options. Set `UsePostgres` to `true` if postgres is desired for
# production/testing/anything
UsePostgres: true
UseMySQL: false
DBHost: localhost
DBPort: "3306"
DBUser: postgres
DBPass: postgres
DBName: testdb
# Redis Options
RedisServer: localhost
RedisPort: 6379
# Whitelist indicates that torrent whitelisting is activated. When torrent
# whitelisting is activated, only pre-approved torrents can be served by
# Notorious. If whitelist is unable to be parsed, we will default to `false`
whitelist: "false"
# UseEnvVariables allows environmental variables to be used instead of
# expliclitly defined config variables.
UseEnvVariables: true
# UseIRCNotify enables announcing new torrents over IRC.
UseIRCNotify: true
IRCNick: "test12765"
IRCPass: "test12765"
IRCServer: "chat.freenode.net"
IRCPort: 6667
IRCChan: "#12765"
